/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chessproject.game;

import java.io.IOException;
import javax.swing.ImageIcon;


/**
 *
 * @author hieup
 */
public class CaroTile extends javax.swing.JPanel {

    /**
     * Creates new form CaroTile
     */
    private final int abscissa;
    private final int ordinate;
    private boolean isTick;
    private boolean isMy;
    public CaroTile(int abscissa, int ordinate) {
        initComponents();
        this.abscissa = abscissa;
        this.ordinate = ordinate;
        isTick = false;
        isMy = false;
    }

    public int getAbscissa() {
        return abscissa;
    }

    public int getOrdinate() {
        return ordinate;
    }

    public boolean isMy() {
        return isMy;
    }

    
    public boolean tick(String imgLink, boolean isMy) throws IOException{
        if(!isTick){
            ImageIcon icon =  new ImageIcon(imgLink, "tick");
            tickLabel.setIcon(icon);
            isTick = true;
            this.isMy = isMy;
            return false;
        }
        return true;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tickLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(25, 25));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(tickLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tickLabel;
    // End of variables declaration//GEN-END:variables
}
